{
  config,
  inputs,
  lib,
  pkgs,
  ...
}: let
  # The DMS package bundles a VS Code theme extension whose theme JSONs are
  # regenerated by DMS's matugen pipeline on every palette/wallpaper change
  # (matugenTemplateVscode defaults to true in DMS — see Common/Theme.qml).
  # We can't install the vsix as a /nix/store-managed extension because
  # matugen needs to write into the extension's themes/ dir at runtime.
  dmsThemeVsix = "${inputs.dms.packages.${pkgs.stdenv.hostPlatform.system}.dms-shell}/share/quickshell/dms/matugen/dms-theme.vsix";
in {
  programs.vscode = {
    enable = true;
    profiles.default.userSettings = {
      "workbench.colorTheme" = "Dynamic Base16 DankShell";

      # Match ghostty (JetBrainsMono Nerd Font + ligatures) so the editor
      # and integrated terminal render the same as the host terminal.
      "editor.fontFamily" = "'JetBrainsMono Nerd Font', 'monospace', monospace";
      "editor.fontSize" = 13;
      "editor.fontLigatures" = true;
      "terminal.integrated.fontFamily" = "JetBrainsMono Nerd Font";

      # Electron's GPU-accelerated text path can look smudged on some
      # GPUs; "dom" uses the browser's native text renderer (sharper at
      # the cost of slightly heavier GPU usage). Worth trying if fonts
      # still look soft after NIXOS_OZONE_WL=1.
      "terminal.integrated.gpuAcceleration" = "on";

      # Disable VS Code's nag prompts that aren't useful in a Nix setup
      # (telemetry, update notifications — nix manages updates).
      "update.mode" = "none";
      "telemetry.telemetryLevel" = "off";
    };
  };

  # Install dms-theme.vsix imperatively into the mutable extensions dir on
  # the first rebuild (and reinstall when the bundled vsix path changes,
  # i.e. after a `nix flake update` of the dms input). The marker symlink
  # makes the check cheap on subsequent rebuilds.
  home.activation.installDmsVscodeTheme = lib.hm.dag.entryAfter ["writeBoundary"] ''
    vsix="${dmsThemeVsix}"
    marker="$HOME/.vscode/extensions/.dms-theme-vsix"
    if [ ! -L "$marker" ] || [ "$(readlink "$marker")" != "$vsix" ]; then
      mkdir -p "$HOME/.vscode/extensions"
      run ${lib.getExe config.programs.vscode.package} --install-extension "$vsix" --force
      run ln -sfn "$vsix" "$marker"
    fi
  '';
}
